name: 'dlyticadbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dlyticadbt'
vars:
  exchange_rate: 139.39
  digital_flag: 'Y'
  interval: 1
  dormant_time: 6
  high_value_threshold: 50000

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dlyticadbt:
    # Config indicated by + and applies to all files under models/example/
    aggregated:
      +materialized: table
      +schema: aggregated
    cleaned:  
      +materialized: view
      +schema: cleaned
    transform:
      +materialized: table
      +schema: transformed
    filter:
      +materialized: table
      +schema: filter